export const SET_CURRENCY_UAH = 'SET_CURRENCY_UAH';
export const SET_CURRENCY_EURO = 'SET_CURRENCY_EURO';
export const SET_CURRENCY_USD = 'SET_CURRENCY_USD';

export const SET_ALL = 'SET_ALL';
export const SET_ONE_TRANSFER = 'SET_ONE_TRANSFER';
export const SET_TWO_TRANSFERS = 'SET_TWO_TRANSFERS';
export const SET_THREE_TRANSFERS = 'SET_THREE_TRANSFERS';
export const SET_WITHOUT_TRANSFERS = 'SET_WITHOUT_TRANSFERS';
